const BASE_COLOR = '#22262a';
const hack = '#ed4631';
const WHITE = '#FFFFFF';
const BRAND_PRIMARY = '#CC9D41';
const BRAND_SECUNDARY = '#FFF';
const DEFAULT_FONT_COLOR = '#393939';
const GRAY = '#C9C9C9';
const DARK_GRAY = '#616161';
const LIGHT_GRAY = '#CBCBCB';
const CRYSTAL_GRAY = '#DBDBDB';
const LIGHTEST_GRAY = '#F0F0F0';
const DARK_BLUE = '#284153';
const LIGHT_BLUE = '#00FFF3';
const BLUE = '#2699FB';
const BROWN = '#813E1A';

const BRAND_INFO = '#62B1F6';
const BRAND_SUCCESS = '#5CB85C';
const BRAND_DANGER = '#C81617';
const BRAND_WARNING = '#F0AD4E';
const BRAND_DARK = '#222';
const BRAND_LIGHT = '#F2F2F2';

export {
  BASE_COLOR,
  BRAND_PRIMARY,
  BRAND_SECUNDARY,
  DEFAULT_FONT_COLOR,
  hack,
  WHITE,
  BLUE,
  GRAY,
  BROWN,
  DARK_GRAY,
  DARK_BLUE,
  LIGHT_BLUE,
  LIGHTEST_GRAY,
  LIGHT_GRAY,
  BRAND_SUCCESS,
  BRAND_DANGER,
  BRAND_WARNING,
  BRAND_INFO,
  BRAND_DARK,
  BRAND_LIGHT,
  CRYSTAL_GRAY,
};
